# Generated by Django 3.1.4 on 2020-12-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
