# Generated by Django 3.1.4 on 2021-01-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0009_auto_20210103_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='issue_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
