# Generated by Django 3.1.4 on 2021-01-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201208_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hours_per_month',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job_type',
            field=models.CharField(default='full_time', max_length=50),
        ),
    ]
