# Generated by Django 3.1.4 on 2021-01-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210103_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='avatar/'),
        ),
    ]
